=== edeposit/edeposit.amqp.aleph_link_export/example/urnnbn_notification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.logica.com/ndk/tm/urnnbn_notification" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.logica.com/ndk/tm/urnnbn_notification">

    <complexType name="Record">
    	<sequence>
    		<element name="docNumber" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="barCode" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="url" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="uuid" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>			
    		<element name="digitalRecords" type="tns:DigitalRecords"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="DigitalRecord">
    	<sequence>
    		<element name="urnnbn" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="url" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="uuid" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    

    <complexType name="Records">
    	<sequence>
    		<element name="record" type="tns:Record"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    	
    </complexType>

    <complexType name="URNNBNNotificationType">
    	<sequence>
    		<element name="batchNumber" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="records" type="tns:Records" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="URNNBNNotification">
    	<complexType>
    		<complexContent>
    			<extension base="tns:URNNBNNotificationType"/>
    		</complexContent>
    	</complexType>
    </element>

    <complexType name="DigitalRecords">
    	<sequence>
    		<element name="digitalRecord" type="tns:DigitalRecord" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== edeposit/edeposit.amqp.aleph_link_export/example/nkp_2015_07_23_23_45_01_522.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<URNNBNNotification xsi:schemaLocation="http://www.logica.com/ndk/tm/urnnbn_notification urnnbn_notification.xsd" xmlns="http://www.logica.com/ndk/tm/urnnbn_notification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <batchNumber>2015_07_23_23_45_01_522</batchNumber>
    <records>
        <record>
            <docNumber>000943247</docNumber>
            <barCode>1002703535</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:00bd84a0-c314-11e4-9541-005056827e51</url>
            <uuid>00bd84a0-c314-11e4-9541-005056827e51</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v58</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:00bd84a0-c314-11e4-9541-005056827e51</url>
                    <uuid>00bd84a0-c314-11e4-9541-005056827e51</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>000135284</docNumber>
            <barCode>1002703978</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:03cf6b50-cbe2-11e4-97af-005056827e51</url>
            <uuid>03cf6b50-cbe2-11e4-97af-005056827e51</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v50</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:03cf6b50-cbe2-11e4-97af-005056827e51</url>
                    <uuid>03cf6b50-cbe2-11e4-97af-005056827e51</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>000561796</docNumber>
            <barCode>1002942835</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:f3bfc840-0831-11e5-a9f6-005056827e52</url>
            <uuid>f3bfc840-0831-11e5-a9f6-005056827e52</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001vfq</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:04ad6e10-df50-11e4-8565-005056827e52</url>
                    <uuid>04ad6e10-df50-11e4-8565-005056827e52</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>000528278</docNumber>
            <barCode>1000255713</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:05a20590-eca9-11e4-b834-005056827e51</url>
            <uuid>05a20590-eca9-11e4-b834-005056827e51</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001vfk</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:05a20590-eca9-11e4-b834-005056827e51</url>
                    <uuid>05a20590-eca9-11e4-b834-005056827e51</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>002597044</docNumber>
            <barCode>1002807637</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:081cc610-cbda-11e4-8565-005056827e52</url>
            <uuid>081cc610-cbda-11e4-8565-005056827e52</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v8o</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:081cc610-cbda-11e4-8565-005056827e52</url>
                    <uuid>081cc610-cbda-11e4-8565-005056827e52</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>002597041</docNumber>
            <barCode>1002807636</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:086d16b0-cbdf-11e4-97af-005056827e51</url>
            <uuid>086d16b0-cbdf-11e4-97af-005056827e51</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001vaq</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:086d16b0-cbdf-11e4-97af-005056827e51</url>
                    <uuid>086d16b0-cbdf-11e4-97af-005056827e51</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>001095937</docNumber>
            <barCode>1002203375</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:0943a980-bd9a-11e4-9541-005056827e51</url>
            <uuid>0943a980-bd9a-11e4-9541-005056827e51</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v1v</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:0943a980-bd9a-11e4-9541-005056827e51</url>
                    <uuid>0943a980-bd9a-11e4-9541-005056827e51</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>000720497</docNumber>
            <barCode>1002703988</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:0a19b870-cbe3-11e4-8565-005056827e52</url>
            <uuid>0a19b870-cbe3-11e4-8565-005056827e52</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v98</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:0a19b870-cbe3-11e4-8565-005056827e52</url>
                    <uuid>0a19b870-cbe3-11e4-8565-005056827e52</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>000713763</docNumber>
            <barCode>1002703962</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:0d28a720-cbd8-11e4-97af-005056827e51</url>
            <uuid>0d28a720-cbd8-11e4-97af-005056827e51</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v8t</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:0d28a720-cbd8-11e4-97af-005056827e51</url>
                    <uuid>0d28a720-cbd8-11e4-97af-005056827e51</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>000672422</docNumber>
            <barCode>1002824092</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:0ede73d0-cbe0-11e4-97af-005056827e51</url>
            <uuid>0ede73d0-cbe0-11e4-97af-005056827e51</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001vby</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:0ede73d0-cbe0-11e4-97af-005056827e51</url>
                    <uuid>0ede73d0-cbe0-11e4-97af-005056827e51</uuid>
                </digitalRecord>
            </digitalRecords>
        </record>
        <record>
            <docNumber>001583621</docNumber>
            <barCode>1001231447</barCode>
            <url>http://kramerius4.nkp.cz/search/handle/uuid:5948ed90-d6af-11e4-8565-005056827e52</url>
            <uuid>5948ed90-d6af-11e4-8565-005056827e52</uuid>
            <digitalRecords>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v9a</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:52853f31-2ee9-11e5-a525-5ef3fc9ae867</url>
                    <uuid>52853f31-2ee9-11e5-a525-5ef3fc9ae867</uuid>
                </digitalRecord>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001va6</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:8fbb1b90-2ee9-11e5-a525-5ef3fc9ae867</url>
                    <uuid>8fbb1b90-2ee9-11e5-a525-5ef3fc9ae867</uuid>
                </digitalRecord>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v9f</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:d23207e0-2ee9-11e5-a525-5ef3fc9ae867</url>
                    <uuid>d23207e0-2ee9-11e5-a525-5ef3fc9ae867</uuid>
                </digitalRecord>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v9b</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:6dbf59b0-2eea-11e5-a525-5ef3fc9ae867</url>
                    <uuid>6dbf59b0-2eea-11e5-a525-5ef3fc9ae867</uuid>
                </digitalRecord>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v9i</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:a8d8e5c0-2eea-11e5-a525-5ef3fc9ae867</url>
                    <uuid>a8d8e5c0-2eea-11e5-a525-5ef3fc9ae867</uuid>
                </digitalRecord>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v9c</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:f55a9f10-2eea-11e5-a525-5ef3fc9ae867</url>
                    <uuid>f55a9f10-2eea-11e5-a525-5ef3fc9ae867</uuid>
                </digitalRecord>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v9g</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:1f8f1090-2eeb-11e5-a525-5ef3fc9ae867</url>
                    <uuid>1f8f1090-2eeb-11e5-a525-5ef3fc9ae867</uuid>
                </digitalRecord>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001vac</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:43bd2650-2eeb-11e5-a525-5ef3fc9ae867</url>
                    <uuid>43bd2650-2eeb-11e5-a525-5ef3fc9ae867</uuid>
                </digitalRecord>
                <digitalRecord>
                    <urnnbn>urn:nbn:cz:nk-001v9e</urnnbn>
                    <url>http://kramerius4.nkp.cz/search/handle/uuid:6dd05430-2eeb-11e5-a525-5ef3fc9ae867</url>
